### ISSUE TITLE
How the palette is sorted?

### ISSUE THREAD

**Issue by xseignard** [olivierlesnicki/quantize#2]
Hello,

Thanks for your lib. I would like to know how the palette is sorted? Is it sorted by most dominant color?

Regards

Xavier

**Comment by olivierlesnicki** [comment]
Yes indeed. The first one being the most dominant one.

**Comment by xseignard** [comment]
Great! Thanks for the quick answer!

**Comment by xseignard** [comment]
I've got one more question, is it possible to directly get the number of each pixels mapped to the reduced palette?

Or do we need to do another pass with `.map(pixel)`  on each pixels?

Regards,

Xavier
